baseURL = "https://rmanzuk.github.io/"
languageCode = "en-us"
title = "Ryan A. Manzuk"
publishDir = "public"
theme = "cactus"

[params]
    colortheme = "white" # Options: dark, light, white, or classic
    description = "Hi! This website is to serve as a forum to succinctly store my work, as well as what I'm currently curious about. Flip to the About page for a blurb, or check out any of the Projects/Discoveries to get a flavor of what I've done."
    mainSection = "projects"
    mainSectionTitle = "Discoveries"
    showAllPostsOnHomePage = false
    postsOnHomePage = 5
    tagsOverview = true
    tocInline = true
    showProjectsList = false  # to use the template's default project list
    googleAnalytics = ""  # Disable it
    logo = "images/ryan_manzuk_headshot.jpg" # point to image to use for logo

[[params.social]]
    name = "github"
    link = "https://github.com/rmanzuk"

[[params.social]]
    name = "email"
    link = "mailto:rmanzuk@princeton.edu"  # Added "mailto:" for proper email links

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/ryan-manzuk"  # Fixed missing "https://"

[params.comments]
    enabled = false

# Main menu which appears below site header.
[[menu.main]]
    name = "Home "
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects "
    url = "/projects"
    weight = 2

[[menu.main]]
    name = "CV "
    url = "/files/cv_rmanzuk.pdf"
    weight = 3
    params = { target = "_blank" }

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 4